name: Main

on:
  push:
    branches: '**'
    tags: '*'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    uses: adya/pack-skse-mod/.github/workflows/pack.yml@main
    with:
      CMAKE_VR_CONFIG_PRESET: ''
      CMAKE_VR_BUILD_PRESET: ''
      FOMOD_INCLUDE_PDB: true
      FOMOD_MOD_NAME: "Enhanced Invisibility"
      FOMOD_MOD_AUTHOR: "powerofthree"
      FOMOD_MOD_NEXUS_ID: "61950"
      FOMOD_SE_MIN_GAME_VERSION: '1.5'
      FOMOD_AE_NAME: 'SSE v1.6+ ("Anniversary Edition")'
      FOMOD_AE_DESCR: 'Select this if you are using Skyrim Anniversary Edition v1.6.640 or higher.'
      FOMOD_AE_MIN_GAME_VERSION: '1.6'
      PUBLISH_ARCHIVE_TYPE: '7z'
      VCPKG_COMMIT_ID: '8ce02b3d9a447071083436ad36f318dd19dd19ad'
